### ISSUE TITLE
Interactable Object Templates

### ISSUE THREAD

**Issue by JPearl-git** [RaphGG/closet-maid#12]
Generic Interactable Object Templates to facilitate product model importation & general use throughout the application.

**TO-DO:**
- [x] Create Expandable & Generic Object Template
- [x] Make Object Template Fully Interactable within UE
- [x] Unit Testing on Object Features
- [x] Move (free,snap,precise)
- [x] Connect (attach objects to one another; merge/detach meshes)
- [x] Measure (identify scale of componenets)
- [x] Detection (identify whether objects are in an acceptable placement or overlapping one another / collision)
