### ISSUE TITLE
2nd TA Check-In

### ISSUE THREAD

**Issue by RaphGG** [RaphGG/closet-maid#6]
2nd TA Check-In of the semester. Useful for gauging how far we come with the Design Document & receiving ample feedback on it.

**TO-DO:**
- [x] Ensure Quality of Writing & Initial Flow of the Document
- [x] Detailed Content is Present & Thought Out
- [x] 120-125 Pages Total - ~25 Pages per Person
- [x] Present 125 pages of Design Document to TA
