### ISSUE TITLE
1st TA Check-In

### ISSUE THREAD

**Issue by RaphGG** [RaphGG/closet-maid#7]
1st TA Check-In of the semester. Useful for for getting started with the design document and receiving quick feedback on it.

**TO-DO:**
- [x] Organize Project Scope & Ideas
- [x] Provide Introduction & Motivations
- [x] Format Initial Design Document
- [x] Present 15 pages of Design Document to TA
