### ISSUE TITLE
Catalog Cleanup

### ISSUE THREAD

**Issue by RaphGG** [RaphGG/closet-maid#70]
**To-Do:**

- [x] Remove Extra Stuff
- [x] Add Different Home Depot Color Options
- [x] Manage/delete presets
- [x] change catalog numbers to CM SKUs
